name: Release Download

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optional: If you have a build step, you can add it here.
      - name: Build
        run: |
          npm install
          npm run build

      - name: Release
        id: release
        uses: sultann/edd-release-download@master
        with:
          site_url: ${{ secrets.SITE_URL }}
          api_key: ${{ secrets.API_KEY }}
          api_token: ${{ secrets.API_TOKEN }}
          item_id: ${{ secrets.ITEM_ID }}

      # After the release, we also want to create a zip and upload it to the release on GitHub.
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        if: ${{ steps.release.outputs.zip_path != '' }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.release.outputs.zip_path }}
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: 'application/zip'
